runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /krait.*
  script: slayers.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest