runtime: python27
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
- url: /crafting.*
  script: slayers.application
- url: /legal
  script: legal.application
- url: /gathering
  static_files: gathering.html
  upload: gathering.html
- url: /
  script: index.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest