runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /krait.*
  script: slayers.application
- url: /legal
  static_files: legal.html
  upload: legal.html
- url: /
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest